const storageKey = "allUsers";
const users = [
  {
    id: 1,
    current_team_id: null,
    role: "owner",
    name: "Ida Schuppe",
    email: "javier76@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "DQPpehYs5V",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 2,
    current_team_id: null,
    role: "owner",
    name: "Natalia Medhurst",
    email: "kswaniawski@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "I9nmBzfpV6",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 3,
    current_team_id: 1,
    role: "admin",
    name: "Dr. Aditya Huels",
    email: "pollich.braulio@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "pbBNkotIZf",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 4,
    current_team_id: 1,
    role: "admin",
    name: "Miss Kendra Kshlerin Jr.",
    email: "glabadie@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "Rnoh8CggsV",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 5,
    current_team_id: 1,
    role: "admin",
    name: "Nathaniel Osinski",
    email: "gdenesik@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "3JmiBYNQzx",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 6,
    current_team_id: 2,
    role: "admin",
    name: "Aaron Volkman",
    email: "angie.skiles@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "nVatiBkRaz",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 7,
    current_team_id: 2,
    role: "admin",
    name: "Dr. Deontae Gleichner",
    email: "tremblay.norval@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "vsFXypnppd",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 8,
    current_team_id: 2,
    role: "admin",
    name: "Darian Sauer DDS",
    email: "shea.reilly@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "XPhh5gTXMV",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 9,
    current_team_id: 3,
    role: "admin",
    name: "Miss Graciela Becker",
    email: "xschamberger@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "b4u1DVVflB",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 10,
    current_team_id: 3,
    role: "admin",
    name: "Ms. Polly Nolan PhD",
    email: "brando.kuphal@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "U121quC6q8",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 11,
    current_team_id: 3,
    role: "admin",
    name: "Ruby Senger",
    email: "rippin.romaine@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token:
      "y70j3LLsF1U0tZsNYMsvAhhLL9YxSof7p0eiGclGynCDpHzjQsWOxJTwb4Ab",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 12,
    current_team_id: null,
    role: "customer",
    name: "Travon Lockman",
    email: "bernadette74@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "3jvUhtC1Fm",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 13,
    current_team_id: null,
    role: "customer",
    name: "Adella Kulas IV",
    email: "curtis56@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "IxpZxIvoXk",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 14,
    current_team_id: null,
    role: "customer",
    name: "Gerald Steuber",
    email: "viola.robel@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "kj6sdyvOSE",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 15,
    current_team_id: null,
    role: "customer",
    name: "Miss Lexi Buckridge",
    email: "flatley.stan@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "yPBIvqAzVI",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 16,
    current_team_id: null,
    role: "customer",
    name: "Edgar Okuneva",
    email: "qbreitenberg@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "hfke16nIz5",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 17,
    current_team_id: null,
    role: "customer",
    name: "Dr. Marty Purdy III",
    email: "rschoen@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "m2hS3Zu9NU",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 18,
    current_team_id: null,
    role: "customer",
    name: "Henry Schowalter",
    email: "bhill@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "ELd5g97ksa",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 19,
    current_team_id: null,
    role: "customer",
    name: "Jasper Ledner MD",
    email: "anjali.upton@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "SiuUzEiqqj",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 20,
    current_team_id: null,
    role: "customer",
    name: "Monroe Hyatt",
    email: "goyette.verner@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "VKtv7xVrrr",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 21,
    current_team_id: null,
    role: "customer",
    name: "Alexie Buckridge",
    email: "moen.hailee@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "xVyf5hjXlS",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 22,
    current_team_id: null,
    role: "customer",
    name: "Mr. Flavio Leuschke IV",
    email: "sdaugherty@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "u1Ca6AhwHU",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 23,
    current_team_id: null,
    role: "customer",
    name: "Gina Effertz",
    email: "mandy.blick@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "GBYHsNlhhD",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 24,
    current_team_id: null,
    role: "customer",
    name: "Lindsey Daugherty",
    email: "selena98@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "WfkJ5szoiM",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 25,
    current_team_id: null,
    role: "customer",
    name: "Tyson O'Hara DVM",
    email: "sgleason@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "8OtGWfP5YR",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 26,
    current_team_id: null,
    role: "customer",
    name: "Joy Towne II",
    email: "gdamore@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "eftgH9f1Z8",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 27,
    current_team_id: null,
    role: "customer",
    name: "Mayra Hauck",
    email: "pstoltenberg@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "RuHkEgCuIX",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 28,
    current_team_id: null,
    role: "customer",
    name: "Dr. Tia Watsica I",
    email: "francis.spinka@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "yree05TBAU",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 29,
    current_team_id: null,
    role: "customer",
    name: "Tito Beatty V",
    email: "ykiehn@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "vgpxW3kIDU",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 30,
    current_team_id: null,
    role: "customer",
    name: "Destini Jenkins",
    email: "rose58@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "SkPUrkoPJK",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 31,
    current_team_id: null,
    role: "customer",
    name: "Arvid Strosin",
    email: "stephania.botsford@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "7KBcf4LJvW",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 32,
    current_team_id: null,
    role: "customer",
    name: "Jaida Mosciski",
    email: "wunsch.troy@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "9k2uAPHvM1",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 33,
    current_team_id: null,
    role: "customer",
    name: "Laurel Greenfelder",
    email: "chaim12@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "QTvOMJLYH5",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 34,
    current_team_id: null,
    role: "customer",
    name: "Claudie Wolff",
    email: "hpollich@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "WZJhC1fT8E",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 35,
    current_team_id: null,
    role: "customer",
    name: "Dr. Lavinia Gottlieb DVM",
    email: "rmorar@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "LKnFzTkAFO",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 36,
    current_team_id: null,
    role: "customer",
    name: "Prof. Johnathan Boyle I",
    email: "rmonahan@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "3dnqsLnx8y",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 37,
    current_team_id: null,
    role: "customer",
    name: "Miss Electa Kling III",
    email: "shannon22@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "oKiAQmnT1L",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 38,
    current_team_id: null,
    role: "customer",
    name: "Ignacio Ratke",
    email: "igoodwin@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "QrbKzUCO0R",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 39,
    current_team_id: null,
    role: "customer",
    name: "Skylar Gibson",
    email: "vschowalter@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "67ZMTIpnHk",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 40,
    current_team_id: null,
    role: "customer",
    name: "Mr. Vince Price",
    email: "xhowe@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "szLhxzBrw9",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 41,
    current_team_id: null,
    role: "customer",
    name: "Orie Parisian",
    email: "kailyn73@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "Xpvz4goiRl",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 42,
    current_team_id: null,
    role: "customer",
    name: "Jennie Bernier",
    email: "ilueilwitz@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "9syy5x7foY",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 43,
    current_team_id: null,
    role: "customer",
    name: "Dr. Jarret Tillman",
    email: "bret.powlowski@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "ngV13wRlH5",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 44,
    current_team_id: null,
    role: "customer",
    name: "Jerrod Auer",
    email: "micaela24@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "U1U44Zx78n",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 45,
    current_team_id: null,
    role: "customer",
    name: "Prof. Dave Herzog II",
    email: "lhintz@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "vvyVKM2zvD",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 46,
    current_team_id: null,
    role: "customer",
    name: "Prof. Elvis Ondricka III",
    email: "morgan.carter@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "CHZBJ7E9PW",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 47,
    current_team_id: null,
    role: "customer",
    name: "Hiram Russel",
    email: "jstark@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "cRLx7pfWYZ",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 48,
    current_team_id: null,
    role: "customer",
    name: "Carolyne Fisher PhD",
    email: "mittie.walsh@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "5KvO3ZBEjV",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 49,
    current_team_id: null,
    role: "customer",
    name: "Coby Turner V",
    email: "mchamplin@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "u6tBBgRAfO",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 50,
    current_team_id: null,
    role: "customer",
    name: "Miss Fleta Strosin",
    email: "eloy.osinski@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "ThjiMdKrxc",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 51,
    current_team_id: null,
    role: "customer",
    name: "Leonel Nader",
    email: "alanna42@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "4r4xUuNpPY",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 52,
    current_team_id: null,
    role: "customer",
    name: "Winifred Mitchell IV",
    email: "srobel@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "uyxfMa6lcs",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 53,
    current_team_id: null,
    role: "customer",
    name: "Dr. Kaitlin Rosenbaum I",
    email: "marcus39@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "rG4TgfpTD8",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 54,
    current_team_id: null,
    role: "customer",
    name: "Quinton Ortiz DDS",
    email: "hgreen@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "1V1TjNtFIO",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 55,
    current_team_id: null,
    role: "customer",
    name: "Mortimer Waelchi",
    email: "kuhlman.gwen@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "OpaYNZyQ5I",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 56,
    current_team_id: null,
    role: "customer",
    name: "King Schultz",
    email: "abagail.bernier@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "6zCWHMDZ0r",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 57,
    current_team_id: null,
    role: "customer",
    name: "Ike Stroman",
    email: "dashawn46@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "rSzwPvzMpv",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 58,
    current_team_id: null,
    role: "customer",
    name: "Prof. Giovani Maggio",
    email: "macejkovic.gustave@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "1SJr46uEPd",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 59,
    current_team_id: null,
    role: "customer",
    name: "Mrs. Selena Schulist",
    email: "morgan.collins@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "k9fM1v2ZVX",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 60,
    current_team_id: null,
    role: "customer",
    name: "Yadira Kling III",
    email: "nienow.zane@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "WOqredfGp7",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 61,
    current_team_id: null,
    role: "customer",
    name: "Mr. Eldred Price IV",
    email: "ike58@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "FANLAV1cQb",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 62,
    current_team_id: null,
    role: "customer",
    name: "Novella Carter",
    email: "lacy45@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "A9I71rUQRB",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 63,
    current_team_id: null,
    role: "customer",
    name: "Orlando Medhurst",
    email: "sister34@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "Q7rUhpntRW",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 64,
    current_team_id: null,
    role: "customer",
    name: "Sister Monahan",
    email: "tierra64@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "Y3w1UTOPdb",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 65,
    current_team_id: null,
    role: "customer",
    name: "Mr. Deangelo Abernathy",
    email: "deion16@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "ONIk2iI4TC",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 66,
    current_team_id: null,
    role: "customer",
    name: "Imogene Dickinson",
    email: "rosemarie84@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "7lCeSgvvpr",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 67,
    current_team_id: null,
    role: "customer",
    name: "Lyla Langworth",
    email: "kozey.verla@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "vjFJXO11hJ",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 68,
    current_team_id: null,
    role: "customer",
    name: "Neoma Ernser II",
    email: "ndaniel@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "CptZFl5LVP",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 69,
    current_team_id: null,
    role: "customer",
    name: "Chelsie Wilkinson",
    email: "jnikolaus@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "GCkST0Pfmg",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 70,
    current_team_id: null,
    role: "customer",
    name: "Rowena Mraz Jr.",
    email: "lily30@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "X3SGRpHfRm",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 71,
    current_team_id: null,
    role: "customer",
    name: "Alex Mraz",
    email: "larkin.jairo@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "ZqurUtHv4B",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 72,
    current_team_id: null,
    role: "customer",
    name: "Gerardo Quigley Jr.",
    email: "greta.predovic@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "2eUccmzn4i",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 73,
    current_team_id: null,
    role: "customer",
    name: "Herbert Ward",
    email: "kyost@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "LxeNS64kxJ",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 74,
    current_team_id: null,
    role: "customer",
    name: "Dr. Arne Prohaska V",
    email: "donnie.ratke@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "cnHr8q8d5p",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 75,
    current_team_id: null,
    role: "customer",
    name: "Paolo Turcotte",
    email: "zstanton@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "V9wuhO4L09",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 76,
    current_team_id: null,
    role: "customer",
    name: "Juana Watsica",
    email: "pattie.graham@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "nv0Zlhb9Cy",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 77,
    current_team_id: null,
    role: "customer",
    name: "Charlie Gibson",
    email: "wilfredo.lind@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "AeFt1PDg5K",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 78,
    current_team_id: null,
    role: "customer",
    name: "Hyman Reynolds",
    email: "maurice10@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "PFOYlUP37l",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 79,
    current_team_id: null,
    role: "customer",
    name: "Godfrey Schultz",
    email: "oschiller@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "C7KsZpVtIB",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 80,
    current_team_id: null,
    role: "customer",
    name: "Bethany Grimes",
    email: "ana58@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "VyEqfAzMyk",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 81,
    current_team_id: null,
    role: "customer",
    name: "Ted Mertz",
    email: "fay.ryann@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "knKLtcIXov",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 82,
    current_team_id: null,
    role: "customer",
    name: "Prof. Ona Heidenreich Jr.",
    email: "maverick.hermiston@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "5kcimXecng",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 83,
    current_team_id: null,
    role: "customer",
    name: "Katlyn Block",
    email: "zpacocha@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "z3vKDZNw1E",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 84,
    current_team_id: null,
    role: "customer",
    name: "Ms. Agustina Ritchie MD",
    email: "asha52@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "YB0RfJYhe1",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 85,
    current_team_id: null,
    role: "customer",
    name: "Angie Mohr",
    email: "ethyl.wehner@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "nJmTknUkN7",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 86,
    current_team_id: null,
    role: "customer",
    name: "Mrs. Karolann Hane",
    email: "elvera.stark@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "89Jo065M2B",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 87,
    current_team_id: null,
    role: "customer",
    name: "Deonte Leuschke",
    email: "desmond.connelly@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "HZS4l311Pf",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 88,
    current_team_id: null,
    role: "customer",
    name: "Alaina Olson",
    email: "barrows.adolph@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "BStFkt8TrZ",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 89,
    current_team_id: null,
    role: "customer",
    name: "Jaunita Bruen",
    email: "nhegmann@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "jkYTmien39",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 90,
    current_team_id: null,
    role: "customer",
    name: "Alejandrin Abernathy",
    email: "deron.flatley@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "8b8FQuNTz3",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 91,
    current_team_id: null,
    role: "customer",
    name: "Dr. Queen Von II",
    email: "wfritsch@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "xUfmgsDbVr",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 92,
    current_team_id: null,
    role: "customer",
    name: "Mr. Lucio Abshire IV",
    email: "sonny.crona@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "Eki6SqkoW4",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 93,
    current_team_id: null,
    role: "customer",
    name: "Schuyler Brekke",
    email: "christian83@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "byKOEWncSL",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 94,
    current_team_id: null,
    role: "customer",
    name: "Reilly Gusikowski",
    email: "maureen30@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "AYom8Nacyg",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 95,
    current_team_id: null,
    role: "customer",
    name: "Kaley Beatty",
    email: "reilly.alisha@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "ihoz3rNg2e",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 96,
    current_team_id: null,
    role: "customer",
    name: "Prof. Connie Schamberger PhD",
    email: "hazel05@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "5dZ7OuflWd",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 97,
    current_team_id: null,
    role: "customer",
    name: "Manuela McClure",
    email: "carley34@example.org",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "Vyt24P67ma",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 98,
    current_team_id: null,
    role: "customer",
    name: "Shanelle Murphy",
    email: "alek.shields@example.net",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "12spDfrCvB",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
  {
    id: 99,
    current_team_id: null,
    role: "customer",
    name: "Mac Swift",
    email: "wmueller@example.com",
    email_verified_at: "2023-05-19 16:31:04",
    google_id: null,
    google_token: null,
    google_refresh_token: null,
    facebook_id: null,
    facebook_token: null,
    facebook_refresh_token: null,
    password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    two_factor_secret: null,
    two_factor_recovery_codes: null,
    two_factor_confirmed_at: null,
    remember_token: "QJk7xfBy5i",
    profile_photo_path: null,
    deleted_at: null,
    created_at: "2023-05-19 16:31:04",
    updated_at: "2023-05-19 16:31:04",
  },
];

const tblContainer = document.getElementById("tblContainer");
const tblBody = tblContainer.getElementsByTagName("tbody")[0];
const tblHeadContainer = tblContainer.getElementsByTagName("thead")[0];
const tblHead = Array.from(tblHeadContainer.getElementsByTagName("th"));
const filterInput = document.getElementById("filterInput");
let allUsers = [];

filterInput.addEventListener("input", filterTable);

tblHead.forEach((th, index) => {
  const arrowIcon = document.createElementNS(
    "http://www.w3.org/2000/svg",
    "svg"
  );
  arrowIcon.setAttribute("width", "10");
  arrowIcon.setAttribute("height", "10");
  arrowIcon.innerHTML = '<path d="M0 4l4-4 4 4z" />';
  arrowIcon.style.display = "none";
  th.appendChild(arrowIcon);

  th.setAttribute("data-sort-direction", "asc");

  th.addEventListener("click", () => {
    sortTable(index, th);
  });
});

function filterTable() {
  const filterValue = filterInput.value.toLowerCase();

  Array.from(tblBody.rows).forEach((row) => {
    const visible = Array.from(row.cells).some((cell) => {
      const cellValue = cell.textContent.toLowerCase();
      return cellValue.includes(filterValue);
    });

    row.style.display = visible ? "" : "none";
  });
}

function sortTable(index, th) {
  const sortDirection = th.getAttribute("data-sort-direction");

  const rows = Array.from(tblBody.rows);
  rows.sort((a, b) => {
    const cellA = a.cells[index].textContent;
    const cellB = b.cells[index].textContent;

    let comparison = 0;

    if (!isNaN(cellA) && !isNaN(cellB)) {
      const numberA = parseFloat(cellA);
      const numberB = parseFloat(cellB);

      if (numberA < numberB) {
        comparison = -1;
      } else if (numberA > numberB) {
        comparison = 1;
      }
    } else {
      comparison = cellA.localeCompare(cellB);
    }

    if (sortDirection === "desc") {
      comparison *= -1;
    }

    return comparison;
  });

  const newSortDirection = sortDirection === "asc" ? "desc" : "asc";
  th.setAttribute("data-sort-direction", newSortDirection);

  const arrowIcon = th.querySelector("svg");
  arrowIcon.style.display = "inline-block";
  arrowIcon.style.transform =
    newSortDirection === "asc" ? "rotate(0deg)" : "rotate(180deg)";

  while (tblBody.firstChild) {
    tblBody.removeChild(tblBody.firstChild);
  }

  rows.forEach((row) => {
    tblBody.appendChild(row);
  });
}

function saveLocalStorage() {
  localStorage.setItem(storageKey, JSON.stringify(users));
}

function retrieveLocalStorage() {
  const savedUsers = localStorage.getItem(storageKey);
  if (savedUsers) {
    allUsers = JSON.parse(savedUsers);
  }
}

function renderTableRows() {
  tblBody.innerHTML = "";

  allUsers.forEach((object, index) => {
    const row = document.createElement("tr");
    const idCell = document.createElement("td");
    const nameCell = document.createElement("td");
    const emailCell = document.createElement("td");
    const roleCell = document.createElement("td");

    idCell.textContent = object.id;
    nameCell.textContent = object.name;
    emailCell.textContent = object.email;
    roleCell.textContent = object.role;

    row.appendChild(idCell);
    row.appendChild(nameCell);
    row.appendChild(emailCell);
    row.appendChild(roleCell);
    tblBody.appendChild(row);
  });
}

function init() {
  console.log("init renderTableRows");

  saveLocalStorage();
  retrieveLocalStorage();
  renderTableRows();
}

init();
